PGAMMAFIT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export PYTHONPATH=$PGAMMAFIT_PATH:$PYTHONPATH
export LD_LIBRARY_PATH=$PGAMMAFIT_PATH/lib:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=$PGAMMAFIT_PATH/lib:$LD_LIBRARY_PATH
echo "PGAMMAFIT_PATH=$PGAMMAFIT_PATH"

